### .github/workflows/github-actions-01.yml

name: Test GitHub Actions-01
run-name: Run GitHub Actions-01
on:
#  push:
  workflow_dispatch
#    branches: 
#      - main
# 지금은 변경 사항이 생기면 기본이 main이라 사용하지 않음

jobs:
  Test-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: step-01
        run: |
          echo "Test GitHub Actions echo-01"
