### github-action-checkout-01.yml

name: Test Github Action checkout-01
run-name: Run Github Action checkout
on:
  push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Print ls
        run: ls -al
        #내 거
      - name: Github Actions Checkout
        uses: actions/checkout@v4
        with:
          path: checkout-dir
        #딴 사람 거
      - name: Github Actions Checkout
        uses: actions/checkout@v4
        with:
          repository: actions/checkout
          path: other-repo
        
      - run: ls -al
      
