### github-action-variable-04.yml

name: Test Github Actions variable-04
run-name: Run Github Actions inputs, outputs, needs
on:
  workflow_dispatch
    inputs:
      name:
        description: '이름'
        required: true
                #필수인 경우 true, 필수 아니면 false
        default: 'INPUT'

jobs:
  input-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print input data
        run: echo "Hello, ${{ github.event.inputs.name }}"
